name: 钉钉推送每天今日说法
on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'
  schedule:
    - cron: "0 06 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests==2.31.0 lxml==5.1.0 pytz==2024.1 selenium==4.18.1

      - name: Run script
        run: python jrsf.py
